### ISSUE TITLE
Integrating with flask-jwt-extended

### ISSUE THREAD

**Issue by krypttr** [miLibris/flask-rest-jsonapi#33]
I'm trying to use flask-jwt-extended for authentication management. I can use jwt_required decorator for Resources and it works fine. However I'm having problems with using identity inside before_update_object method. I can load the current identity with get_jwt_identity() and it is dictionary. However if I try to access a key within the dictionary it throws an error. It works fine in before_create_object method though.

```
class StuffDetail(ResourceDetail):
    def before_update_object(self, obj, data, view_kwargs):
        current_user = get_jwt_identity()
        if int(obj.user.id != current_user.id):
            raise JsonApiException(detail="You are not authorized to edit this resource.",
                                   status=403,
                                   title="Authorization Error")

    schema = StuffSchema
    data_layer = {'session': db.session,
                  'model': Stuff,
                  'methods': {''before_update_object' : before_update_object}
                  }
    decorators = (jwt_required,)
```

```
Traceback (most recent call last):
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\WEB\Project1\flask\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\WEB\Project1\flask\lib\site-packages\flask_jwt_extended\view_decorators.py", line 35, in wrapper
    return fn(*args, **kwargs)
  File "E:\WEB\Project1\flask\lib\site-packages\flask_rest_jsonapi\decorators.py", line 32, in wrapper
    return func(*args, **kwargs)
  File "E:\WEB\Project1\flask\lib\site-packages\flask\views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "E:\WEB\Project1\flask\lib\site-packages\flask_rest_jsonapi\resource.py", line 72, in dispatch_request
    raise e
TypeError: __init__() takes at least 3 arguments (4 given)

```

**Comment by akira-dev** [comment]
I think this error comes from your JsonApiException initialization. Try this:
```python
class StuffDetail(ResourceDetail):
    def before_update_object(self, obj, data, view_kwargs):
        current_user = get_jwt_identity()
        if int(obj.user.id != current_user.id):
            raise JsonApiException('', 
                                   detail="You are not authorized to edit this resource.",
                                   status=403,
                                   title="Authorization Error")

    schema = StuffSchema
    data_layer = {'session': db.session,
                  'model': Stuff,
                  'methods': {''before_update_object' : before_update_object}
                  }
    decorators = (jwt_required,)
```

**Comment by krypttr** [comment]
Oh, wow! How did I miss that? Thank you very much and sorry for bothering you.
