### ISSUE TITLE
before_post() is throwing TypeError

### ISSUE THREAD

**Issue by gsverma** [miLibris/flask-rest-jsonapi#79]
```
def before_post(data=None, *args, **kwargs):
          if not data:
              raise ObjectNotFound({'parameter': 'data'},
                                   "Not a POST request or No data supplied")
 
          code = data['data']['attributes']['code']
          publisher = self.session.query(Device).filter_by(code=code).first()
          if not publisher:
              raise ObjectNotFound({'parameter': 'code'},
                                   "No publisher device found with provided code")
 
          publisher_id = publisher.id
          data['data']['attributes']['publisher_id'] = publisher_id
          del data['data']['attributes']['code']

          pass
```

This throws- 

`Traceback (most recent call last):
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask_rest_jsonapi/decorators.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask_rest_jsonapi/resource.py", line 77, in dispatch_request
    raise e
TypeError: before_post() got multiple values for keyword argument 'data'`

I have tried `before_post(args, kwargs, data=None)` too. Same result. Please, let me know if I have missed something. Using 0.13.2 as of now.

**Comment by gsverma** [comment]
can someone let me know what other options are available while making dict for post_schema_kwargs other then 'only'. 

I have updated above before_post(data=None, *args, **kwargs) to before_post(*args, **kwargs). 
But, I need to delete 'code' before POST, as code is not in db model.
post_schema_kwargs = {'only':('code', 'subscriber_id', )}  
so is there a way I can delete 'code' in kwargs before POST. Or, a better way to make 'code' available in kwargs without modifying model. 'Coz if I don't mention post_schema_kwargs as above; the kwargs['data']['code'] fields gets omitted from the request dict. 

My sample request json is: 

`{
	"data": {
		"type": "subscriptions",
		"attributes": {
			"code": "8P0F4K2",
			"subscriber_id": 1
		
		}
	}
}`

**Comment by gsverma** [comment]
As one of workaround I tried `post_schema_kwargs = {'only':(Device.code, 'subscriber_id', )}`

It gives: 

`Traceback (most recent call last):
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/Flask_REST_JSONAPI-0.13.2-py2.7.egg/flask_rest_jsonapi/decorators.py", line 33, in wrapper
    return func(*args, **kwargs)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/var/www/html/vrxis_rest_json/lib/python2.7/site-packages/Flask_REST_JSONAPI-0.13.2-py2.7.egg/flask_rest_jsonapi/resource.py", line 77, in dispatch_request
    raise e
NotImplementedError: Operator 'contains' is not supported on this expression
`

A more simple way it seems is to just put a dummy Subscription.code in db and continue to use Device.code.

**Comment by akira-dev** [comment]
For before_post you have to use the exact same method signature:
```python
def before_post(self, args, kwargs, data=None):
    pass
```

For your question: can someone let me know what other options are available while making dict for post_schema_kwargs other then 'only'.
Options available on schema a listed in marsmallow documentation
